# Generated by Django 4.2.7 on 2024-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcard',
            name='addreportcard',
            field=models.IntegerField(default=0),
        ),
    ]
